data_analysis_task:
  description: >
    CRITICAL: Execute in exact order. Do not skip any step.

    STEP 1 - DATABASE STATISTICAL ANALYSIS (MANDATORY):
    1. Call "Database Statistical Analysis Tool" with: {"analysis_type": "descriptive"}
    2. Call "Database Statistical Analysis Tool" with: {"analysis_type": "data_quality"}
    3. Call "Database Statistical Analysis Tool" with: {"analysis_type": "distribution", "target_column": "Class"}

    STEP 2 - GUARANTEED VISUALIZATIONS (MANDATORY):
    4. Call "Guaranteed Visualizations Tool" with: {"task_name": "data_analysis_task"}

    This single call generates ALL required images:
    - fraud_comparison.png
    - correlation_heatmap.png

    STEP 3 - VALIDATION (MANDATORY):
    5. Call "Task Validation Tool" with: {"task_name": "data_analysis_task", "required_images": ["fraud_comparison", "correlation_heatmap"], "validation_type": "images_exist"}

    Execute ALL steps in order. The Guaranteed Visualizations Tool ensures deterministic image generation.
  expected_output: >
    A detailed statistical analysis report in markdown format including:
    - Dataset overview (number of transactions, features, data types)
    - Statistical summaries for all features in table format
    - Data quality assessment (missing values, outliers)
    - Distribution analysis of fraud vs legitimate transactions (if Class column exists)
    - Key findings and data preprocessing recommendations
    MUST include these visualizations using the Fraud Detection Visualization Tool:
    - Create a 'fraud_comparison' chart showing fraud vs legitimate transaction counts
    - Create a 'distribution' chart showing transaction amount distributions
    - Create a 'correlation_heatmap' for feature correlations
    Include all chart images in the markdown report with proper image references
  agent: data_analyst

pattern_recognition_task:
  description: >
    CRITICAL: Execute in exact order. Do not skip any step.

    STEP 1 - DATABASE CORRELATION ANALYSIS (MANDATORY):
    1. Call "Database Statistical Analysis Tool" with: {"analysis_type": "correlation"}

    STEP 2 - GUARANTEED VISUALIZATIONS (MANDATORY):
    2. Call "Guaranteed Visualizations Tool" with: {"task_name": "pattern_recognition_task"}

    This single call generates ALL required images:
    - scatter.png (Feature relationships)
    - time_series.png (Fraud incidents over time)
    - feature_importance.png (Most predictive features)
    - box_plot.png (Distribution comparison)

    STEP 3 - VALIDATION (MANDATORY):
    3. Call "Task Validation Tool" with: {"task_name": "pattern_recognition_task", "required_images": ["scatter", "time_series", "feature_importance", "box_plot"], "validation_type": "images_exist"}

    Execute ALL steps in order. The Guaranteed Visualizations Tool ensures deterministic image generation.
  expected_output: >
    A comprehensive pattern analysis report in markdown format including:
    - Identified fraud patterns and their characteristics in table format
    - Unusual transaction patterns and anomalies
    - Feature correlations that indicate fraud
    - Time-based fraud patterns
    - Amount-based fraud indicators
    - Recommended rules or thresholds for fraud detection
    MUST include these visualizations using the Fraud Detection Visualization Tool:
    - Create a 'scatter' plot showing relationship between key features
    - Create a 'time_series' chart for fraud incidents over time
    - Create a 'feature_importance' chart highlighting most predictive features
    - Create a 'box_plot' comparing feature distributions by class
    Include all chart images in the markdown report with proper image references
  agent: pattern_recognition_agent

classification_task:
  description: >
    CRITICAL: Execute in exact order. Do not skip any step.

    STEP 1 - DATABASE OUTLIER ANALYSIS (MANDATORY):
    1. Call "Database Statistical Analysis Tool" with: {"analysis_type": "outliers"}

    STEP 2 - GUARANTEED VISUALIZATIONS (MANDATORY):
    2. Call "Guaranteed Visualizations Tool" with: {"task_name": "classification_task"}

    This single call generates ALL required images:
    - amount_histogram.png (Transaction amount distribution)

    STEP 3 - VALIDATION (MANDATORY):
    3. Call "Task Validation Tool" with: {"task_name": "classification_task", "required_images": ["amount_histogram"], "validation_type": "images_exist"}

    Execute ALL steps in order. The Guaranteed Visualizations Tool ensures deterministic image generation.
  expected_output: >
    A classification analysis report in markdown format including:
    - Classification methodology and criteria used
    - Summary statistics of classifications in table format (number of fraud vs legitimate)
    - Confidence levels and uncertainty analysis with tables
    - Risk assessment for different transaction types
    - Recommendations for threshold adjustments
    - Cost-benefit analysis of classification decisions
    MUST include this visualization using the Fraud Detection Visualization Tool:
    - Create a 'histogram' chart showing confidence score distributions
    Include the chart image in the markdown report with proper image reference
  agent: classification_agent

reporting_task:
  description: >
    Create a comprehensive fraud detection analysis report. You MUST execute ALL steps in order.

    STEP 1 - MANDATORY - Get Available Images:
    Call "Image Verification Tool" with: {"action": "list_available"}
    COPY the exact markdown references from the tool output table.

    STEP 2 - MANDATORY - Create Report:
    Write a comprehensive report including findings from previous agents:

    # Fraud Detection Analysis Report

    ## Executive Summary
    [Include key findings and business recommendations]

    ## Methodology
    [Describe the 4-step analysis process]

    ## Data Analysis Results
    [Include correlation heatmap and fraud comparison using EXACT references from Step 1]

    ## Pattern Recognition Results
    [Include scatter plot, time series, and feature importance using EXACT references from Step 1]

    ## Classification Analysis
    [Include histogram using EXACT references from Step 1]

    ## Risk Assessment and Recommendations
    [Business recommendations and strategies]

    CRITICAL: Use ONLY the exact markdown image references provided by Step 1 tool output. Do NOT create new image references.

    STEP 3 - MANDATORY - Format Final Report:
    Call "Markdown Formatter Tool" with: {"markdown_content": "[paste your complete report from step 2]"}

    SUBMIT ONLY the formatted output from Step 3 as your final response.
  expected_output: >
    A comprehensive fraud detection report in markdown format that includes:

    - ALL 6 available images with exact markdown references from Image Verification Tool
    - Findings from previous agent analyses
    - Proper markdown formatting from Markdown Formatter Tool
    - Content organized in sections: Executive Summary, Methodology, Data Analysis, Pattern Recognition, Classification Analysis, Risk Assessment

    CRITICAL REQUIREMENTS:
    1. Must include ALL available images: correlation_heatmap.png, fraud_comparison.png, scatter.png, time_series.png, feature_importance.png, amount_histogram.png
    2. Must use exact markdown references from Image Verification Tool output
    3. Must be formatted by Markdown Formatter Tool
    4. Must NOT reference non-existent images
  agent: reporting_analyst
